/// action_controls_reset()

setting_key_new = new_shortcut(ord("N"), true, false)
setting_key_new_template = new_shortcut(ord("N"), true, true)
setting_key_open = new_shortcut(ord("O"), true, false)
setting_key_save = new_shortcut(ord("S"), true, false)
setting_key_save_as = new_shortcut(ord("S"), true, true)
setting_key_import = new_shortcut(ord("I"), true, false)

setting_key_undo = new_shortcut(ord("Z"), true, false)
setting_key_redo = new_shortcut(ord("Y"), true, false)
setting_key_rename = new_shortcut(vk_f2, false, false)
setting_key_delete = new_shortcut(vk_delete, false, false)
setting_key_duplicate = new_shortcut(ord("D"), true, false)
setting_key_select_all = new_shortcut(ord("A"), true, false)
setting_key_uv_editor = new_shortcut(ord("E"), true, false)

setting_key_tool_select = new_shortcut(ord("W"), false, false)
setting_key_tool_pivot = new_shortcut(ord("Q"), false, false)
setting_key_tool_move = new_shortcut(ord("G"), false, false)
setting_key_tool_rotate = new_shortcut(ord("R"), false, false)
setting_key_tool_scale = new_shortcut(ord("S"), false, false)
setting_key_tool_transform = new_shortcut(ord("T"), false, false)
setting_key_tool_bend = new_shortcut(ord("B"), false, false)
setting_key_tool_resize = new_shortcut(ord("Z"), false, false)
setting_key_snap = new_shortcut(ord("F"), false, false)

setting_key_walk_navigation = new_shortcut(ord("F"), false, true)
setting_key_forward = new_shortcut(ord("W"), false, false)
setting_key_back = new_shortcut(ord("S"), false, false)
setting_key_left = new_shortcut(ord("A"), false, false)
setting_key_right = new_shortcut(ord("D"), false, false)
setting_key_ascend = new_shortcut(ord("E"), false, false)
setting_key_descend = new_shortcut(ord("Q"), false, false)
setting_key_reset = new_shortcut(ord("R"), false, false)
setting_key_fast = new_shortcut(vk_space, false, false)
setting_key_slow = new_shortcut(vk_lshift, false, false)
